
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.55.1'
version_full = '76720bf88350c70b99ab3d4272d01bd9f14eeace'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

